import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import Section2D from '../components/Section2D/Section2D'
import Section3D from '../components/Section3D/Section3D'
import Sidebar from '../components/Sidebar/Sidebar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />          
      </Head>
      
      <main className='container-fluid'>
        <div className='row'>
          <Header/>

          <div className='col-md-12'>
            <div className='row'>
              <Sidebar />
              <Section2D />
              <Section3D />
            </div>
          </div>
          <Footer content={'Footer'}/>          
        </div>        
      </main>
      
    </div>
  )
}

export default Home
